module Main where

/*
protocol BazProtocol = Baz
protocol FooProtocol = Foo

actor FooActor Foo where
    BazProtocol -> baz
    FooProtocol -> foo
*/

printer a :: (Show a) => [a] -> String
printer a = show a

main = do
    a <- 4 + 5
    b <- 4.0 + 5.9
    c <- "4" + "5"
    print "{} {} {}" % (a, b, c)
    //bs <- ["a", "5"]
    //print (show "5")
    //print (show bs)
   // print (show "a")
    