[package]
name = "siko"
version = "0.1.0"
authors = ["no <nope>"]
edition = "2018"

[dependencies]
siko_compiler = { path = "../siko_compiler" }
siko_constants = { path = "../siko_constants" }

walkdir = "2"
colored = "1.7.0"
