[package]
name = "siko_transpiler"
version = "0.1.0"
authors = ["no <nope>"]
edition = "2018"

[dependencies]
siko_util = { path = "../siko_util" }
siko_mir = { path = "../siko_mir" }
siko_constants = { path = "../siko_constants" }
