name: Master

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: ./tests.sh
    - name: Run comp tests
      run: ./comp_tests.sh
